apps/ansible_task/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from .views import RunModule,GetInverntoryHost,PlayBookRun,PlaybooksAdd,AnsibleLogView
from .views import PlayBookList,PlayBookUpload,RoleDetail,RoleList,RoleUpdate,RoleAdd,RoleDel
from .views import PathCreate,PathDel,PlayBookDetail,GetFileContent,PlayBookDel
from .views import check_name,ModuleLogDel,PlayBookLogDel
from .views import InventoryDelView,InventoryUpdateView,InventoryListView,InventoryAddView
urlpatterns = [
    url(r'^inventory/list/$', InventoryListView.as_view(),name='inventory_list'),
    url(r'^inventory/add/$', InventoryAddView.as_view(), name='inventory_add'),
    url(r'^inventory/update/(?P<pk>\d+)/$', InventoryUpdateView.as_view(), name='inventory_update'),
    url(r'^inventory/delete/(?P<pk>\d+)/$', InventoryDelView.as_view(), name='inventory_delete'),
    url(r'^run_module/$', RunModule.as_view(), name='run_module'),
    url(r'^run_log/$', AnsibleLogView.as_view(), name='run_log'),
    url(r'^playbook/add/$', PlaybooksAdd.as_view(), name='playbook_add'),
    url(r'^playbook/upload/$', PlayBookUpload.as_view(), name='playbook_upload'),
    url(r'^playbook/list/$', PlayBookList.as_view(), name='playbook_list'),
    url(r'^role/detail/(?P<pk>[0-9]+)/$', RoleDetail.as_view(), name='role_detail'),
    url(r'^role/list/$', RoleList.as_view(), name='role_list'),
    url(r'^role/edit/$', RoleUpdate.as_view(), name='role_edit'),
    url(r'^role/add/$', RoleAdd.as_view(), name='role_add'),
    url(r'^path/del/$', PathDel.as_view(), name='path_del'),
    url(r'^path/create/$', PathCreate.as_view(), name='path_create'),
    url(r'^get_file_content/$', GetFileContent.as_view(), name='get_file_content'),
    url(r'^playbook/run/(?P<pk>[0-9]+)/$', PlayBookRun.as_view(), name='playbook_run'),
    url(r'^playbook/info/(?P<pk>[0-9]+)/$', PlayBookDetail.as_view(), name='playbook_info'),
    url(r'^playbook/del/(?P<pk>[0-9]+)/$', PlayBookDel.as_view(), name='playbook_del'),
    url(r'^role/del/(?P<pk>[0-9]+)/$', RoleDel.as_view(), name='role_del'),
    url(r'^playbook_log_del/$', PlayBookLogDel.as_view(), name='playbook_log_del'),
    url(r'^module_log_del/$', ModuleLogDel.as_view(), name='module_log_del'),
    url(r'^check_name/$', check_name, name='check_name'),
    url(r'^get_inventory_hosts/$',GetInverntoryHost.as_view() , name='get_inventory_hosts')
]

apps/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import UserListView,RoleListView,MenuListView,UserProfileView
from .views import RoleAddView,MenuAddView,PermissionAddView,UserRegisterView
from .views import RoleUpdateView,MenuUpdateView,PermissionUpdateView,UserUpdatateView
from .views import RoleDelView,MenuDelView,PermissionDelView,UserDelView
from .views import SecondMenuAddView,SecondMenuDelView,SecondMenuUpdateView,multi_permissions,multi_permissions_del,distribute_permissions
urlpatterns = [
    url(r'^user/register/$', UserRegisterView.as_view(),name='register'),
    url(r'^user/list/$',UserListView.as_view(),name='user_list'),
    url(r'^user/profile/$',UserProfileView.as_view(),name='user_profile'),
    url(r'^menu/list/$',MenuListView.as_view(),name='menu_list'),
    url(r'^role/list/$',RoleListView.as_view(),name='role_list'),
    #url(r'^hostper/list/$',HostPermissionList.as_view(),name='hostper_list'),
    url(r'^role/add/$',RoleAddView.as_view(),name='role_add'),
    url(r'^menu/add/$',MenuAddView.as_view(),name='menu_add'),
    url(r'^permission/add/(?P<second_menu_id>\d+)/$',PermissionAddView.as_view(),name='permission_add'),
    #url(r'^hostper/add/$',HostPermissionCreate.as_view(),name='hostper_add'),
    url(r'^user/update/(?P<pk>[0-9]+)/$',UserUpdatateView.as_view(),name='user_update'),
    url(r'^role/update/(?P<pk>[0-9]+)/$',RoleUpdateView.as_view(),name='role_update'),
    url(r'^menu/update/(?P<pk>[0-9]+)/$',MenuUpdateView.as_view(),name='menu_update'),
    #url(r'^hostper/update/(?P<pk>[0-9]+)/$',HostPermissionUpdate.as_view(),name='hostper_update'),
    url(r'^permission/update/(?P<pk>[0-9]+)/$',PermissionUpdateView.as_view(),name='permission_update'),
    url(r'^user/delete/(?P<pk>[0-9]+)/$',UserDelView.as_view(),name='user_delete'),
    url(r'^role/delete/(?P<pk>[0-9]+)/$',RoleDelView.as_view(),name='role_delete'),
    url(r'^menu/delete/(?P<pk>[0-9]+)/$',MenuDelView.as_view(),name='menu_delete'),
    #url(r'^hostper/delete/(?P<pk>[0-9]+)/$',HostPermissionDel.as_view(),name='hostper_delete'),
    url(r'^permission/delete/(?P<pk>[0-9]+)/$',PermissionDelView.as_view(),name='permission_delete'),
    url(r'^multi/permissions/$', multi_permissions, name='multi_permissions'),
    url(r'^multi/permissions/delete/(?P<pk>\d+)/$', multi_permissions_del, name='multi_permissions_delete'),
    url(r'^distribute/permissions/$', distribute_permissions, name='distribute_permissions'),
    url(r'^second/menu/add/(?P<menu_id>\d+)$', SecondMenuAddView.as_view(), name='second_menu_add'),
    url(r'^second/menu/update/(?P<pk>\d+)/$', SecondMenuUpdateView.as_view(), name='second_menu_update'),
    url(r'^second/menu/delete/(?P<pk>\d+)/$', SecondMenuDelView.as_view(), name='second_menu_delete'),
    ]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

opadmin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .settings import MEDIA_ROOT,DEBUG

from django.views.static import serve
from rest_framework.documentation import include_docs_urls
from rest_framework.routers import  DefaultRouter

from rest_framework_jwt.views import obtain_jwt_token
from asset.api import HostGroupViewSet,HostUserViewSet,HostViewSet,IDCViewSet
from users.api import UserInfoViewSet,RoleViewSet,PermissionViewSet,MenuViewSet
from webterminal.api import AuditLogViewSet,CommandlogViewSet
from workplan.api import OperationLogViewSet,CdnLogViewSet
from ansible_task.api import InventoryViewSet
from django.views.generic import TemplateView

router = DefaultRouter()
router.register(r'assets',HostViewSet,base_name='assets'),
router.register(r'idc',IDCViewSet,base_name='idc')
router.register(r'group',HostGroupViewSet,base_name='group')
router.register(r'remoteuser',HostUserViewSet,base_name='remoteuser')

router.register(r'users',UserInfoViewSet,base_name='users')
#router.register(r'hostpermission',PermissionViewSet,base_name='hostpermission')
router.register(r'menu',MenuViewSet,base_name='menu')
router.register(r'permission',PermissionViewSet,base_name='permission')
router.register(r'role',RoleViewSet,base_name='role')

router.register(r'auditlog',AuditLogViewSet,base_name='auditlog')
router.register(r'commandlog',CommandlogViewSet,base_name='commandlog')

router.register(r'operaticonlog',OperationLogViewSet,base_name='operaticonlog')
router.register(r'cdnlog',CdnLogViewSet,base_name='cdnlog')
router.register(r'inventory',InventoryViewSet,base_name='Inventory')

import xadmin
xadmin.autodiscover()

from xadmin.plugins import xversion
xversion.register_models()

from users.views import LoginView,Dashboard,LogoutView,WxLogin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', include(xadmin.site.urls)),  # 添加新路由
    #django默认认证
    url(r'^api-auth/', include('rest_framework.urls')),
    #rest文档页
    url(r'docs/',include_docs_urls(title="OMS")),
    #路由
    url(r'^api/', include(router.urls)),
    #jwt的认证接口,用于获取token   header加入Authorization: JWT <your_token>
    url(r'^jwt_login/$', obtain_jwt_token),
    #url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    #url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^wxlogin/$',WxLogin.as_view(),name='wxlogin'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^index/$',Dashboard.as_view(),name='index'),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^work/',include('workplan.urls',namespace='workplan')),
    url(r'^host/',include('asset.urls',namespace='host')),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^webssh/',include('webterminal.urls',namespace='webssh')),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
    url(r'^wiki/',include('wiki.urls',namespace='wiki')),
    url(r'^task/',include('ansible_task.urls',namespace='ansible_task')),
    url(r'^db/',include('db_operation.urls',namespace='db')),
    url(r'^pro/',include('probuild.urls',namespace='pro')),
]
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
if DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, { 'document_root': MEDIA_ROOT, }),
    ]

templates/task/role_add.html
{% extends 'layout.html' %}

{% block page_title %}新增角色{% endblock %}
{% block title %}新增角色{% endblock %}
/{% block custom_css %}
    <link rel="stylesheet" href="/static/ztree/css/metroStyle/metroStyle.css">
    <link rel="stylesheet" href="/static/jquery-confirm/dist/jquery-confirm.min.css/">
    <style>
        #playbook-editor {
            width: 100%;
            height: 600px;
        }

        .col-md-4 button {
            width: 80px;
            margin-top: 5px;
            float: right;
            clear: right;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="wrapper wrapper-content animated fadeIn">

            <div class="row">
                <div class="col-lg-12">
                <div class="ibox ">
                        <div class="ibox-title">
                            <h5>新增角色</h5>
                        </div>
                        <div class="ibox-content">
                            <div class="col-md-4">
                        <ul id="roleTree" class="ztree" style="float: left"></ul>
                        <button type="button" class="btn btn-success btn-xs" id="addParent" onclick="return false;">
                            增加父节点
                        </button>
                        <button type="button" class="btn btn-success btn-xs" id="addLeaf" onclick="return false;">增加子节点
                        </button>
                        <button type="button" class="btn btn-warning btn-xs" id="edit" onclick="return false;">编辑名称
                        </button>
                        <button type="button" class="btn btn-danger btn-xs" id="remove" onclick="return false;">删除节点
                        </button>
                        <a href="{% url 'ansible_task:role_list' %}">
                            <button type="button" class="btn btn-primary btn-xs">编辑完成</button>
                        </a>
                    </div>
                            <div class="col-md-8">
                        <div class="box-header relative_path" style="padding: 3px;">

                        </div>
                        <div id="playbook-editor"></div>
                    </div>
                        </div>
                </div>
                </div>
            </div>
    </div>
{% endblock %}


{% block js %}
    <script src="/static/ztree/js/jquery.ztree.all.js"></script>
    <script src="/static/ace/js/ace.js"></script>
    <script src="/static/ace/js/mode-yaml.js"></script>
    <script src="/static/ace/js/theme-monokai.js"></script>
    <script src="/static/jquery-confirm/dist/jquery-confirm.min.js"></script>
    <script>
    $(function () {
        $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
    });
        let setting = {
            view: {
                selectedMulti: false
            },
            edit: {
                enable: true,
                showRemoveBtn: false,
                showRenameBtn: false
            },
            data: {
                keep: {
                    parent: true,
                    leaf: true
                },
                simpleData: {
                    enable: true
                }
            },
            callback: {
                beforeRemove: beforeRemove,
                onClick: onClick,
                beforeRename: beforeRename,
            },
        };

        let nodes = [
            {id: 1, pId: 0, name: "{{ name }}", open: true, p_name: "{{ root_path }}"},
        ];

        let dirs = ["defaults", "files", "handlers", "meta", "tasks", "templates", "vars"];
        for (let i = 0; i < dirs.length; i++) {
            if (dirs[i] === "files" || dirs[i] === "templates") {
                nodes.push({
                    id: 11,
                    pId: 1,
                    name: dirs[i],
                    isParent: true,
                    open: true,
                    p_name: "{{ root_path }}/{{ name }}"
                });
            } else {
                nodes.push({
                    id: 11,
                    pId: 1,
                    name: dirs[i],
                    isParent: true,
                    open: true,
                    p_name: "{{ root_path }}/{{ name }}",
                    children: [{
                        name: "main.yml",
                        p_name: "{{ root_path }}/{{ name }}/" + dirs[i]
                    }]
                });
            }
        }

        function beforeRemove(treeId, treeNode) {
            return confirm("确认删除 节点 -- " + treeNode.name + " 吗？");
        }

        function beforeRename(treeId, treeNode, newName) {
            if (newName.length === 0) {
                alert("节点名称不能为空.");
                let zTree = $.fn.zTree.getZTreeObj("roleTree");
                setTimeout(function () {
                    zTree.editName(treeNode)
                }, 10);
                return false;
            } else {
                $.ajax({
                    url: "{% url 'ansible_task:path_create' %}",
                    type: 'POST',
                    data: {
                        name: treeNode.name,
                        p_name: treeNode.p_name,
                        isParent: treeNode.isParent,
                        new_name: newName
                    },
                    error: function (res) {
                        $.alert({
                            title: 'Tips',
                            type: 'red',
                            content: '添加失败！' + res.responseText,
                        })
                    }
                });
                return true;
            }
        }

        let newCount = 1;

        function add(e) {
            let zTree = $.fn.zTree.getZTreeObj("roleTree"),
                isParent = e.data.isParent,
                nodes = zTree.getSelectedNodes(),
                treeNode = nodes[0];
            if (treeNode) {
                if (treeNode.isParent) {
                    treeNode = zTree.addNodes(treeNode, {
                        id: (100 + newCount),
                        pId: treeNode.id,
                        isParent: isParent,
                        name: "new node" + (newCount++),
                        p_name: treeNode.p_name + '/' + treeNode.name
                    });
                    zTree.editName(treeNode[0]);
                } else {
                    alert("叶子节点被锁定，无法增加子节点");
                }
            } else {
                alert("请先选择一个节点");
            }
        }

        function edit() {
            let zTree = $.fn.zTree.getZTreeObj("roleTree"),
                nodes = zTree.getSelectedNodes(),
                treeNode = nodes[0];
            if (nodes.length === 0) {
                alert("请先选择一个节点");
                return;
            }
            zTree.editName(treeNode);
        }

        function remove(e) {
            let zTree = $.fn.zTree.getZTreeObj("roleTree"),
                nodes = zTree.getSelectedNodes(),
                treeNode = nodes[0];
            if (nodes.length === 0) {
                alert("请先选择一个节点");
                return;
            }
            $.ajax({
                url: "{% url 'ansible_task:path_del' %}",
                type: 'POST',
                data: {name: treeNode.name, p_name: treeNode.p_name},
                success: function (res) {
                    if (res.status) {
                        zTree.removeNode(treeNode, true);
                    }
                },
                error: function (data) {
                    $.alert({
                        title: 'Tips',
                        type: 'red',
                        content: '删除失败！' + data.responseText,
                    })
                }
            });
        }

        function onClick(event, treeId, treeNode, clickFlag) {
            if (!treeNode.isParent) {
                let relative_path = $('.relative_path');
                relative_path.html('');
                relative_path.append(`<p class="text-green" style="text-align: center;margin-bottom: 0;float: left;">当前文件是：${treeNode.p_name}/${treeNode.name}</p>------<button type="button" class="btn btn-success btn-xs save" data-toggle="tooltip" title="只有点击保存，文件才会创建"> 确认保存</button>`);

                $("[data-toggle='tooltip']").tooltip();
                let editor = ace.edit("playbook-editor");
                editor.setTheme("ace/theme/monokai");
                let YamlMode = ace.require("ace/mode/yaml").Mode;
                editor.session.setMode(new YamlMode());
                editor.setShowPrintMargin(false);

                $.ajax({
                    url: "{% url 'ansible_task:get_file_content' %}",
                    type: 'POST',
                    data: {p_name: treeNode.p_name, name: treeNode.name},
                    success: function (res) {
                        if (res.status) {
                            editor.setValue(res.content, -1);
                        } else {
                            editor.setValue("", -1);
                        }
                    }
                });

                $('.save').on('click', function () {
                    $.ajax({
                        url: "{% url 'ansible_task:role_edit' %}",
                        type: 'POST',
                        data: {content: editor.getSession().getValue(), p_name: treeNode.p_name, name: treeNode.name},
                        success: function (res) {
                            if (res.status) {
                                $.alert({
                                    title: 'Tips',
                                    type: 'green',
                                    content: res.msg,
                                })
                            } else {
                                $.alert({
                                    title: 'Tips',
                                    type: 'red',
                                    content: res.msg,
                                })
                            }
                        }
                    })
                });
            }
        }

        $(document).ready(function () {
            $.fn.zTree.init($("#roleTree"), setting, nodes);
            $("#addParent").bind("click", {isParent: true}, add);
            $("#addLeaf").bind("click", {isParent: false}, add);
            $("#edit").bind("click", edit);
            $("#remove").bind("click", remove);
        });
    </script>
{% endblock %}

templates/task/role_detail.html
{% extends 'layout.html' %}
{% block title %}角色详情{% endblock %}
{% block page_title %}角色详情{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" href="/static/ztree/css/metroStyle/metroStyle.css">
    <link rel="stylesheet" href="/static/jquery-confirm/dist/jquery-confirm.min.css">
    <style>
        #playbook-editor {
            width: 100%;
            height: 600px;
        }

        .col-md-4 button {
            width: 80px;
            margin-top: 5px;
            float: right;
            clear: right;
        }
    </style>
{% endblock %}


{% block content %}
        <div class="wrapper wrapper-content animated fadeIn">

            <div class="row">
                <div class="col-lg-12">
                <div class="ibox ">
                        <div class="ibox-title">
                            <h5>角色详情</h5>
                        </div>
                        <div class="ibox-content">
                            <div class="col-md-4">
                        <ul id="roleTree" class="ztree" style="float: left"></ul>
                        <button type="button" class="btn btn-success btn-xs" id="addParent" onclick="return false;">
                            增加父节点
                        </button>
                        <button type="button" class="btn btn-success btn-xs" id="addLeaf" onclick="return false;">增加子节点
                        </button>
                        <button type="button" class="btn btn-warning btn-xs" id="edit" onclick="return false;">编辑名称
                        </button>
                        <button type="button" class="btn btn-danger btn-xs" id="remove" onclick="return false;">删除节点
                        </button>
                        <a href="{% url 'ansible_task:role_list' %}">
                            <button type="button" class="btn btn-primary btn-xs">编辑完成</button>
                        </a>
                    </div>
                            <div class="col-md-8">
                        <div class="box-header relative_path" style="padding: 3px;">

                        </div>
                        <div id="playbook-editor"></div>
                    </div>
                        </div>
                </div>
                </div>
            </div>
        </div>

{% endblock %}


{% block custom_js %}
    <script src="/static/ztree/js/jquery.ztree.all.js"></script>
    <script src="/static/ace/js/ace.js"></script>
    <script src="/static/ace/js/mode-yaml.js"></script>
    <script src="/static/ace/js/theme-monokai.js"></script>
    <script src="/static/jquery-confirm/dist/jquery-confirm.min.js"></script>
    <script>
    $(function () {
        $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
    });
        let setting = {
            view: {
                selectedMulti: false
            },
            edit: {
                enable: true,
                showRemoveBtn: false,
                showRenameBtn: false
            },
            async: {
                enable: true,
                type: "post",
                url: "{% url 'ansible_task:role_detail' pk %}",
                autoParam: ["name", "p_name"],
            },
            data: {
                keep: {
                    parent: true,
                    leaf: true
                },
                simpleData: {
                    enable: true
                }
            },
            callback: {
                beforeRemove: beforeRemove,
                onClick: onClick,
                onAsyncError: onAsyncError,
                beforeRename: beforeRename,
            },
        };

        function beforeRemove(treeId, treeNode) {
            return confirm("确认删除 节点 -- " + treeNode.name + " 吗？");
        }

        function beforeRename(treeId, treeNode, newName) {
            if (newName.length === 0) {
                alert("节点名称不能为空.");
                let zTree = $.fn.zTree.getZTreeObj("roleTree");
                setTimeout(function () {
                    zTree.editName(treeNode)
                }, 10);
                return false;
            } else {
                $.ajax({
                    url: "{% url 'ansible_task:path_create' %}",
                    type: 'POST',
                    data: {
                        name: treeNode.name,
                        p_name: treeNode.p_name,
                        isParent: treeNode.isParent,
                        new_name: newName
                    },
                    error: function (res) {
                        $.alert({
                            title: 'Tips',
                            type: 'red',
                            content: '添加失败！' + res.responseText,
                        })
                    }
                });
                return true;
            }
        }

        let newCount = 1;

        function add(e) {
            let zTree = $.fn.zTree.getZTreeObj("roleTree"),
                isParent = e.data.isParent,
                nodes = zTree.getSelectedNodes(),
                treeNode = nodes[0];
            if (treeNode) {
                if (treeNode.isParent) {
                    treeNode = zTree.addNodes(treeNode, {
                        id: (100 + newCount),
                        pId: treeNode.id,
                        isParent: isParent,
                        name: "new node" + (newCount++),
                        p_name: treeNode.p_name + '/' + treeNode.name
                    });
                    zTree.editName(treeNode[0]);
                } else {
                    alert("叶子节点被锁定，无法增加子节点");
                }
            } else {
                alert("请先选择一个节点");
            }
        }

        function edit() {
            let zTree = $.fn.zTree.getZTreeObj("roleTree"),
                nodes = zTree.getSelectedNodes(),
                treeNode = nodes[0];
            if (nodes.length === 0) {
                alert("请先选择一个节点");
                return;
            }
            zTree.editName(treeNode);
        }

        function remove(e) {
            let zTree = $.fn.zTree.getZTreeObj("roleTree"),
                nodes = zTree.getSelectedNodes(),
                treeNode = nodes[0];
            if (nodes.length === 0) {
                alert("请先选择一个节点");
                return;
            }
            $.ajax({
                url: "{% url 'ansible_task:path_del' %}",
                type: 'POST',
                data: {name: treeNode.name, p_name: treeNode.p_name},
                success: function (res) {
                    if (res.status) {
                        zTree.removeNode(treeNode, true);
                    }
                },
                error: function (data) {
                    $.alert({
                        title: 'Tips',
                        type: 'red',
                        content: '删除失败！' + data.responseText,
                    })
                }
            });
        }

        function onClick(event, treeId, treeNode, clickFlag) {
            if (!treeNode.isParent) {
                let relative_path = $('.relative_path');
                relative_path.html('');

                let editor = ace.edit("playbook-editor");
                editor.setTheme("ace/theme/monokai");
                let YamlMode = ace.require("ace/mode/yaml").Mode;
                editor.session.setMode(new YamlMode());
                editor.setShowPrintMargin(false);
                editor.setReadOnly(true);

                $.ajax({
                    url: "{% url 'ansible_task:get_file_content' %}",
                    type: 'POST',
                    data: {p_name: treeNode.p_name, name: treeNode.name},
                    success: function (res) {
                        relative_path.append(`<p class="text-green" style="text-align: center;margin-bottom: 0;float: left;">当前文件是：${res.relative_path}</p>------<button type="button" class="btn btn-primary btn-xs editor"> 启用编辑</button> <button type="button" class="btn btn-warning btn-xs save"> 确认修改</button>`);

                        if (res.status) {
                            editor.setValue(res.content, -1);
                        } else {
                            editor.setValue("", -1);
                        }

                        $('.editor').on('click', function () {
                            editor.setReadOnly(false);
                        });

                        $('.save').on('click', function () {
                            $.ajax({
                                url: "{% url 'ansible_task:role_edit' %}",
                                type: 'POST',
                                data: {content: editor.getSession().getValue(), relative_path: res.relative_path},
                                success: function (res) {
                                    if (res.status) {
                                        $.confirm({
                                            title: 'Tips',
                                            content: res.msg,
                                            type: 'green',
                                            buttons: {
                                                Ok: function () {
                                                    editor.setReadOnly(true);
                                                },
                                            }
                                        });
                                    } else {
                                        $.alert({
                                            title: 'Tips',
                                            type: 'red',
                                            content: res.msg,
                                        })
                                    }
                                }
                            })
                        });

                    }
                });
            }
        }

        function onAsyncError() {
            $.confirm({
                title: 'Tips',
                content: "该role文件夹在服务器上不存在，请删除数据库记录！",
                type: 'red',
                buttons: {
                    Ok: function () {
                        location.href = "{% url 'ansible_task:role_list' %}"
                    },
                }
            });
        }

        $(document).ready(function () {
            zTreeObj = $.fn.zTree.init($("#roleTree"), setting);
            $("#addParent").bind("click", {isParent: true}, add);
            $("#addLeaf").bind("click", {isParent: false}, add);
            $("#edit").bind("click", edit);
            $("#remove").bind("click", remove);
        });
    </script>

{% endblock %}