apps/wiki/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from .views import DocAddView,DocUpdateView,DocDetailView,DocListView,DocDelView
urlpatterns = [
    url(r'^doc/list/$',DocListView.as_view(),name='doc_list'),
    url(r'^doc/detail/(?P<pk>[0-9]+)/$',DocDetailView.as_view(),name='doc_detail'),
    url(r'^doc/add/$',DocAddView.as_view(),name='doc_add'),
    url(r'^doc/update/(?P<pk>[0-9]+)/$',DocUpdateView.as_view(),name='doc_update'),
    url(r'^doc/delete/(?P<pk>[0-9]+)/$',DocDelView.as_view(),name='doc_delete'),
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

opadmin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .settings import MEDIA_ROOT,DEBUG

from django.views.static import serve
from rest_framework.documentation import include_docs_urls
from rest_framework.routers import  DefaultRouter

from rest_framework_jwt.views import obtain_jwt_token
from asset.api import HostGroupViewSet,HostUserViewSet,HostViewSet,IDCViewSet
from users.api import UserInfoViewSet,RoleViewSet,PermissionViewSet,MenuViewSet
from webterminal.api import AuditLogViewSet,CommandlogViewSet
from workplan.api import OperationLogViewSet,CdnLogViewSet
from ansible_task.api import InventoryViewSet
from django.views.generic import TemplateView

router = DefaultRouter()
router.register(r'assets',HostViewSet,base_name='assets'),
router.register(r'idc',IDCViewSet,base_name='idc')
router.register(r'group',HostGroupViewSet,base_name='group')
router.register(r'remoteuser',HostUserViewSet,base_name='remoteuser')

router.register(r'users',UserInfoViewSet,base_name='users')
#router.register(r'hostpermission',PermissionViewSet,base_name='hostpermission')
router.register(r'menu',MenuViewSet,base_name='menu')
router.register(r'permission',PermissionViewSet,base_name='permission')
router.register(r'role',RoleViewSet,base_name='role')

router.register(r'auditlog',AuditLogViewSet,base_name='auditlog')
router.register(r'commandlog',CommandlogViewSet,base_name='commandlog')

router.register(r'operaticonlog',OperationLogViewSet,base_name='operaticonlog')
router.register(r'cdnlog',CdnLogViewSet,base_name='cdnlog')
router.register(r'inventory',InventoryViewSet,base_name='Inventory')

import xadmin
xadmin.autodiscover()

from xadmin.plugins import xversion
xversion.register_models()

from users.views import LoginView,Dashboard,LogoutView,WxLogin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', include(xadmin.site.urls)),  # 添加新路由
    #django默认认证
    url(r'^api-auth/', include('rest_framework.urls')),
    #rest文档页
    url(r'docs/',include_docs_urls(title="OMS")),
    #路由
    url(r'^api/', include(router.urls)),
    #jwt的认证接口,用于获取token   header加入Authorization: JWT <your_token>
    url(r'^jwt_login/$', obtain_jwt_token),
    #url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    #url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^wxlogin/$',WxLogin.as_view(),name='wxlogin'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^index/$',Dashboard.as_view(),name='index'),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^work/',include('workplan.urls',namespace='workplan')),
    url(r'^host/',include('asset.urls',namespace='host')),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^webssh/',include('webterminal.urls',namespace='webssh')),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
    url(r'^wiki/',include('wiki.urls',namespace='wiki')),
    url(r'^task/',include('ansible_task.urls',namespace='ansible_task')),
    url(r'^db/',include('db_operation.urls',namespace='db')),
    url(r'^pro/',include('probuild.urls',namespace='pro')),
]
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
if DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, { 'document_root': MEDIA_ROOT, }),
    ]

apps/wiki/models.py
from django.db import models
from django.contrib.auth import get_user_model
from datetime import datetime
from DjangoUeditor.models import UEditorField
User = get_user_model()
# Create your models here.

class Documents(models.Model):
    title =models.CharField(max_length=128,verbose_name=u'文档标题',unique=True)
    content = UEditorField(width=600, height=300, toolbars="full", imagePath="wiki/images/", filePath="wiki/files/",upload_settings={"imageMaxSize":1204000},settings={},verbose_name='内容')
    author = models.CharField(max_length=32,verbose_name='作者')
    ctime = models.DateTimeField(default=datetime.now,verbose_name='发表时间')
    utime = models.DateTimeField(auto_now=True,verbose_name='修改时间')
    def __str__(self):
        return self.title
    class Meta:
        db_table ='wiki'
        verbose_name = 'WiKi文档'
        verbose_name_plural = verbose_name

apps/wiki/forms.py
# -*- coding:utf-8 -*-
from .models import Documents
from django import  forms
from django.forms import widgets
from  DjangoUeditor.widgets import UEditorWidget
from DjangoUeditor.forms import UEditorField
class DocumentForm(forms.ModelForm):
    author = forms.CharField(label='作者',widget=widgets.TextInput(attrs={'class':'form-control'}))
    title = forms.CharField(label='标题',max_length=128,widget=widgets.TextInput(attrs={'class':'form-control'}))
    content = UEditorField(label='内容',width=950,height=300, toolbars="full", imagePath="wiki/images/", filePath="wiki/files/",upload_settings={"imageMaxSize": 1204000}, settings={})
    class Meta:
        model = Documents
        fields = ['title','content','author']

apps/wiki/views.py
from .models import Documents
from .forms import DocumentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView,View,UpdateView,CreateView,DeleteView,TemplateView,DetailView
from django.shortcuts import render,redirect,HttpResponse
from pure_pagination import PageNotAnInteger,EmptyPage,Paginator
import markdown
from django.core.urlresolvers import reverse_lazy
import logging
logger = logging.getLogger(__name__)
# Create your views here.

class DocListView(LoginRequiredMixin,ListView):
    template_name = 'wiki/doc.html'
    model = Documents
    context_object_name = 'all_docs'
    queryset = Documents.objects.all()
    ordering = ('-id')

    def get_queryset(self):
        self.queryset = super().get_queryset()
        try:
            page = self.request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(self.queryset, 10, request=self.request)
        self.queryset = p.page(page)
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super(DocListView, self).get_context_data()
        context['title'] = '文档列表'
        return context

class DocDetailView(LoginRequiredMixin,DetailView):
    model = Documents
    template_name = 'wiki/doc_detail.html'
    context_object_name =  '文章详情'
    def get_object(self, queryset=None):
        obj = super(DocDetailView,self).get_object()
        obj.content = markdown.markdown(obj.content.replace("\r\n", '  \n'),extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ],safe_mode=True,enable_attributes=False)
        return obj


class DocAddView(LoginRequiredMixin,CreateView):
    '''文档添加'''
    model = Documents
    form_class = DocumentForm
    template_name =  'user/change.html'
    success_url = reverse_lazy('wiki:doc_list')
    def get_context_data(self, **kwargs):
        context = super(DocAddView,self).get_context_data()
        context['title'] = '新增文档'
        return  context
    def get_initial(self):
        initial = super(DocAddView, self).get_initial()
        initial['author'] = self.request.user.name
        return initial
    def get_form(self, form_class=None):
        form = super(DocAddView, self).get_form(form_class)
        form.fields['author'].widget.attrs.update({'readonly': True})
        return form
class DocUpdateView(LoginRequiredMixin,UpdateView):
    '''文档修改'''
    model = Documents
    form_class = DocumentForm
    template_name = 'user/change.html'
    success_url = reverse_lazy('wiki:doc_list')
    def get_context_data(self, **kwargs):
        context = super(DocUpdateView,self).get_context_data()
        context['title'] = '更新文档'
        return  context
    def get_form(self, form_class=None):
        form = super(DocUpdateView, self).get_form(form_class)
        form.fields['author'].widget.attrs.update({'readonly': True})
        return form
class DocDelView(LoginRequiredMixin,DeleteView):

    '''文档删除'''
    model = Documents
    template_name = 'user/delete.html'
    success_url = reverse_lazy('wiki:doc_list')
    raise_exception = True
    def get_context_data(self, **kwargs):
        context = super(DocDelView,self).get_context_data()
        context['cancel'] = reverse_lazy('wiki:doc_list')
        context['title'] = '删除文档'
        return  context

templates/wiki/doc.html
{%  extends 'layout.html' %}

{% block title %}
   {{ title }}
{%  endblock %}
{% block page_title %}{{ title }}{% endblock %}
{% block  content %}
<div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox ">
                        <div class="ibox-title">
                            <h5>{{ title }}</h5>
                        </div>
                        <div class="ibox-content">
                            <div style="margin-bottom: 10px">
                                <a href="{% url    'wiki:doc_add' %}" class="btn btn-sm btn-primary ">添加文档</a>
                            </div>

                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>标题</th>
                                    <th>作者</th>
                                    <th>发表时间</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {%  for doc in  all_docs.object_list %}
                                <tr id="{{ doc.id }}">
                                    <td>{{ doc.id }}</td>
                                    <td>{{ doc.title }}</td>
                                    <td>{{ doc.author }}</td>
                                    <td>{{ doc.ctime }}</td>
                                    <td class="text-navy">
                                        <a class="btn btn-xs btn-info" href="{% url 'wiki:doc_detail' doc.id %}">查看文档</a>
                                <a class="btn btn-xs btn-info" href="{% url 'wiki:doc_update' doc.id %}">更新文档</a>
                                <a class="btn btn-xs btn-danger" href="{% url 'wiki:doc_delete' doc.id %}">删除文档</a>
                            </td>

                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
                <div class="pageturn">
                 <ul class="pagelist">
          {% if all_docs.has_previous %}
            <li class="long"><a href="?{{ all_docs.previous_page_number.querystring }}">上一页</a></li>
        {% endif %}

        {% for page in all_docs.pages %}
            {% if page %}
                {% ifequal page all_docs.number %}
                    <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                {% else %}
                    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                {% endifequal %}
            {% else %}
                <li class="none"><a href="">...</a></li>
            {% endif %}
        {% endfor %}
        {% if all_docs.has_next %}
            <li class="long"><a href="?{{ all_docs.next_page_number.querystring }}">下一页</a></li>
        {% endif %}
    </ul>
</div>
            </div>
        </div>
{%  endblock %}

templates/wiki/doc_detail.html
{% extends 'layout.html' %}

{% block custom_css %}
    <link rel="stylesheet" href="/static/highlight/styles/github.css">
<link rel="stylesheet" href="/static/highlight/styles/code.css">
    <!--SyntaxHighlighter的基本脚本-->
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shCore.js"></script>
<!--SyntaxHighlighter的对各个编程语言解析的脚本-->
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushJScript.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushPhp.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushJava.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushCSharp.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushCpp.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushAS3.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushPython.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushVb.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushSql.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushXml.js"></script>
<script type="text/javascript" src="/static/syntaxhighlighter/scripts/shBrushPlain.js"></script>
<!--所使用的SyntaxHighlighter样式-->
<link type="text/css" rel="stylesheet" href="/static/syntaxhighlighter/styles/shCoreEclipse.css"/>
<!--初始化SyntaxHighlighter的必须代码，必须放在head中，引入文件之后-->
<script type="text/javascript">SyntaxHighlighter.all();</script>
<!--用于消除右上角的广告-->
<script type="text/javascript">SyntaxHighlighter.defaults['toolbar'] = false;</script>
    <style>
        .col-md-3 {
            position: fixed;
            right: 0;
            width: 300px;
            margin-left: 15px;
        }

        .blog-item-meta li {
            margin: 5px 15px;
            display: inline;
            list-style-type: none;
            white-space: nowrap;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row" style="margin-left: 15px; margin-right: 15px;">

        <div class="col-md-12">
            <div class="box box-primary">
                <article class="card mb-4">
                    <header class="card-header text-center">
                        <h1 class="card-title">{{ object.title }}</h1>
                        {% if request.user.name == object.author %}
                            <div class="card-meta">
                                <a href="{% url 'wiki:doc_update' object.id %}">编辑&nbsp;&nbsp;</a>
                            </div>
                        {% endif %}
                            <ul class="blog-item-meta" style="margin-top: 5px;margin-bottom: 5px">
                                <li><i class="fa fa-user-o"></i>By <a
                                        href="javascript:void(0)">{{ object.author}}</a></li>
                                <li><i class="fa fa-calendar-o"></i> {{ object.ctime|date:"Y-m-d" }}</li>

                            </ul>

                    </header>

                    <div class="card-body" style="margin-left: 15px;margin-right: 15px;">
                        {{ object.content|safe }}
                    </div>
                </article>
            </div>
        </div>

    </div>
{% endblock %}