apps/asset/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from .views import HostListView,HostImportView,DownloadTplView,IdcListView,HostUserListView,HostGroupListView,UserHostPerListView
from .views import HostUpdateView,IdcUpdateView,HostUserUpdateView,HostGroupUpdateView,UserHostPerAddView
from .views import HostDelView,HostGroupDelView,IdcDelView,HostUserDelView,UserHostPerDelView
from  .views import HostAddView,IdcAddView,HostGroupAddView,HostUserAddView,UserHostPerUpdateView
from .views import WebSSH,AssetTableView
urlpatterns = [
    url(r'^host/list/$', HostListView.as_view(),name='host_list'),
    url(r'^hostper/list',UserHostPerListView.as_view(),name='user_host_list'),
    url(r'^import/$',HostImportView.as_view(),name='import'),
    url(r'^tpl/$',DownloadTplView.as_view(),name='tpl'),
    url(r'^idc/list/$',IdcListView.as_view(),name='idc_list'),
    url(r'^hostuser/list/$',HostUserListView.as_view(),name='hostuser_list'),
    url(r'^hostgroup/list/$',HostGroupListView.as_view(),name='hostgroup_list'),
    url(r'^host/add/$',HostAddView.as_view(),name='host_add'),
    url(r'^hostper/add/$',UserHostPerAddView.as_view(),name='hostper_add'),
    url(r'^hostper/update/(?P<pk>\d+)/$',UserHostPerUpdateView.as_view(),name='hostper_update'),
    url(r'^host/update/(?P<pk>\d+)/$',HostUpdateView.as_view(),name='host_update'),
    url(r'^host/delete/(?P<pk>\d+)/$',HostDelView.as_view(),name='host_delete'),
    url(r'^hostgroup/add/$',HostGroupAddView.as_view(),name='hostgroup_add'),
    url(r'^hostgroup/update/(?P<pk>\d+)/$',HostGroupUpdateView.as_view(),name='hostgroup_update'),
    url(r'^hostgroup/delete/(?P<pk>\d+)/$',HostGroupDelView.as_view(),name='hostgroup_delete'),
    url(r'^hostuser/add/$',HostUserAddView.as_view(),name='hostuser_add'),
    url(r'^hostuser/update/(?P<pk>\d+)/$',HostUserUpdateView.as_view(),name='hostuser_update'),
    url(r'^hostuser/delete/(?P<pk>\d+)/$',HostUserDelView.as_view(),name='hostuser_delete'),
    url(r'^idc/add/$',IdcAddView.as_view(),name='idc_add'),
    url(r'^idc/update/(?P<pk>\d+)/$',IdcUpdateView.as_view(),name='idc_update'),
    url(r'^idc/delete/(?P<pk>\d+)/$',IdcDelView.as_view(),name='idc_delete'),
    url(r'^hostper/delete/(?P<pk>\d+)/$',UserHostPerDelView.as_view(),name='hostper_delete'),
    url(r'^webssh/$',WebSSH.as_view(),name='webssh'),
    url(r'^assetjson/$',AssetTableView.as_view(),name='assetjson'),
    ]

apps/users/service/urls.py
# -*- coding:utf-8 -*-

from django.urls import reverse
from django.http import QueryDict


def memory_url(request, name, *args, **kwargs):
    """
    生成带有原搜索条件的URL（替代了模板中的url）
    :param request:
    :param name:
    :return:
    """
    basic_url = reverse(name, args=args, kwargs=kwargs)

    # 当前URL中无参数
    if not request.GET:
        return basic_url

    query_dict = QueryDict(mutable=True)
    query_dict['_filter'] = request.GET.urlencode()  # mid=2&age=99

    return "%s?%s" % (basic_url, query_dict.urlencode())


def memory_reverse(request, name, *args, **kwargs):
    """
    反向生成URL
        http://127.0.0.1:8001/rbac/menu/add/?_filter=mid%3D2
        1. 在url中讲原来搜索条件，如filter后的值
        2. reverse生成原来的URL，如：/menu/list/
        3. /menu/list/?mid%3D2

    示例：
    :param request:
    :param name:
    :param args:
    :param kwargs:
    :return:
    """
    url = reverse(name, args=args, kwargs=kwargs)
    origin_params = request.GET.get('_filter')
    if origin_params:
        url = "%s?%s" % (url, origin_params,)

    return url

apps/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import UserListView,RoleListView,MenuListView,UserProfileView
from .views import RoleAddView,MenuAddView,PermissionAddView,UserRegisterView
from .views import RoleUpdateView,MenuUpdateView,PermissionUpdateView,UserUpdatateView
from .views import RoleDelView,MenuDelView,PermissionDelView,UserDelView
from .views import SecondMenuAddView,SecondMenuDelView,SecondMenuUpdateView,multi_permissions,multi_permissions_del,distribute_permissions
urlpatterns = [
    url(r'^user/register/$', UserRegisterView.as_view(),name='register'),
    url(r'^user/list/$',UserListView.as_view(),name='user_list'),
    url(r'^user/profile/$',UserProfileView.as_view(),name='user_profile'),
    url(r'^menu/list/$',MenuListView.as_view(),name='menu_list'),
    url(r'^role/list/$',RoleListView.as_view(),name='role_list'),
    #url(r'^hostper/list/$',HostPermissionList.as_view(),name='hostper_list'),
    url(r'^role/add/$',RoleAddView.as_view(),name='role_add'),
    url(r'^menu/add/$',MenuAddView.as_view(),name='menu_add'),
    url(r'^permission/add/(?P<second_menu_id>\d+)/$',PermissionAddView.as_view(),name='permission_add'),
    #url(r'^hostper/add/$',HostPermissionCreate.as_view(),name='hostper_add'),
    url(r'^user/update/(?P<pk>[0-9]+)/$',UserUpdatateView.as_view(),name='user_update'),
    url(r'^role/update/(?P<pk>[0-9]+)/$',RoleUpdateView.as_view(),name='role_update'),
    url(r'^menu/update/(?P<pk>[0-9]+)/$',MenuUpdateView.as_view(),name='menu_update'),
    #url(r'^hostper/update/(?P<pk>[0-9]+)/$',HostPermissionUpdate.as_view(),name='hostper_update'),
    url(r'^permission/update/(?P<pk>[0-9]+)/$',PermissionUpdateView.as_view(),name='permission_update'),
    url(r'^user/delete/(?P<pk>[0-9]+)/$',UserDelView.as_view(),name='user_delete'),
    url(r'^role/delete/(?P<pk>[0-9]+)/$',RoleDelView.as_view(),name='role_delete'),
    url(r'^menu/delete/(?P<pk>[0-9]+)/$',MenuDelView.as_view(),name='menu_delete'),
    #url(r'^hostper/delete/(?P<pk>[0-9]+)/$',HostPermissionDel.as_view(),name='hostper_delete'),
    url(r'^permission/delete/(?P<pk>[0-9]+)/$',PermissionDelView.as_view(),name='permission_delete'),
    url(r'^multi/permissions/$', multi_permissions, name='multi_permissions'),
    url(r'^multi/permissions/delete/(?P<pk>\d+)/$', multi_permissions_del, name='multi_permissions_delete'),
    url(r'^distribute/permissions/$', distribute_permissions, name='distribute_permissions'),
    url(r'^second/menu/add/(?P<menu_id>\d+)$', SecondMenuAddView.as_view(), name='second_menu_add'),
    url(r'^second/menu/update/(?P<pk>\d+)/$', SecondMenuUpdateView.as_view(), name='second_menu_update'),
    url(r'^second/menu/delete/(?P<pk>\d+)/$', SecondMenuDelView.as_view(), name='second_menu_delete'),
    ]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

opadmin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .settings import MEDIA_ROOT,DEBUG

from django.views.static import serve
from rest_framework.documentation import include_docs_urls
from rest_framework.routers import  DefaultRouter

from rest_framework_jwt.views import obtain_jwt_token
from asset.api import HostGroupViewSet,HostUserViewSet,HostViewSet,IDCViewSet
from users.api import UserInfoViewSet,RoleViewSet,PermissionViewSet,MenuViewSet
from webterminal.api import AuditLogViewSet,CommandlogViewSet
from workplan.api import OperationLogViewSet,CdnLogViewSet
from ansible_task.api import InventoryViewSet
from django.views.generic import TemplateView

router = DefaultRouter()
router.register(r'assets',HostViewSet,base_name='assets'),
router.register(r'idc',IDCViewSet,base_name='idc')
router.register(r'group',HostGroupViewSet,base_name='group')
router.register(r'remoteuser',HostUserViewSet,base_name='remoteuser')

router.register(r'users',UserInfoViewSet,base_name='users')
#router.register(r'hostpermission',PermissionViewSet,base_name='hostpermission')
router.register(r'menu',MenuViewSet,base_name='menu')
router.register(r'permission',PermissionViewSet,base_name='permission')
router.register(r'role',RoleViewSet,base_name='role')

router.register(r'auditlog',AuditLogViewSet,base_name='auditlog')
router.register(r'commandlog',CommandlogViewSet,base_name='commandlog')

router.register(r'operaticonlog',OperationLogViewSet,base_name='operaticonlog')
router.register(r'cdnlog',CdnLogViewSet,base_name='cdnlog')
router.register(r'inventory',InventoryViewSet,base_name='Inventory')

import xadmin
xadmin.autodiscover()

from xadmin.plugins import xversion
xversion.register_models()

from users.views import LoginView,Dashboard,LogoutView,WxLogin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', include(xadmin.site.urls)),  # 添加新路由
    #django默认认证
    url(r'^api-auth/', include('rest_framework.urls')),
    #rest文档页
    url(r'docs/',include_docs_urls(title="OMS")),
    #路由
    url(r'^api/', include(router.urls)),
    #jwt的认证接口,用于获取token   header加入Authorization: JWT <your_token>
    url(r'^jwt_login/$', obtain_jwt_token),
    #url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    #url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^wxlogin/$',WxLogin.as_view(),name='wxlogin'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^index/$',Dashboard.as_view(),name='index'),
    url(r'^elfinder/', include('elfinder.urls')),
    url(r'^work/',include('workplan.urls',namespace='workplan')),
    url(r'^host/',include('asset.urls',namespace='host')),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^webssh/',include('webterminal.urls',namespace='webssh')),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
    url(r'^wiki/',include('wiki.urls',namespace='wiki')),
    url(r'^task/',include('ansible_task.urls',namespace='ansible_task')),
    url(r'^db/',include('db_operation.urls',namespace='db')),
    url(r'^pro/',include('probuild.urls',namespace='pro')),
]
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
if DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, { 'document_root': MEDIA_ROOT, }),
    ]

apps/asset/models.py
from django.db import models
from django.core.exceptions import ValidationError
from datetime import datetime
from utils import crypt_password
import uuid
from django.utils.text import slugify
import random
import string
# Create your models here.

class IDC(models.Model):
    name = models.CharField(max_length=32,unique=True,verbose_name=u'机房',error_messages={'unique':'该机房已存在，请不要重复添加'})
    servers = models.ManyToManyField('Hosts')
    ctime = models.DateTimeField(default=datetime.now,verbose_name=u'创建时间')
    utime = models.DateTimeField(auto_now=True,verbose_name=u'更新时间')
    def __str__(self):
        return self.name

    class Meta:
        db_table = 'idc'
        verbose_name = u'机房'
        verbose_name_plural = verbose_name
class Hosts(models.Model):
    ASSET_STATUS = (
        ('online','上线'),
        ('offline','下线')
    )
    ASSET_TYPE = (
        ('physical','物理机'),
        ('virtual','虚拟机'),
        ('instance','云主机')
    )
    hostname = models.CharField(max_length=32,verbose_name='主机名',unique={'unique':'主机名已存在'})
    server_type = models.CharField(choices=ASSET_TYPE,default='instance',max_length=10,verbose_name=u'服务器类型')
    wip = models.GenericIPAddressField(verbose_name=u'外网IP',unique=True,error_messages={'blank':'外网地址不能为空','unique':'该外网地址已存在'})
    nip = models.GenericIPAddressField(verbose_name=u'内网IP',unique=True,error_messages={'blank':'内网地址不能为空','unique':'该内网地址已存在'})
    status = models.CharField(max_length=10,choices=ASSET_STATUS,default='offline',verbose_name='状态')
    instance_id = models.CharField(max_length=64,verbose_name=u'云服务器ID',blank=True,null=True)
    sn = models.CharField(max_length=64,blank=True,null=True,verbose_name='SN编号')
    cpu_info = models.CharField(max_length=128,verbose_name='CPU',blank=True,null=True)
    os = models.CharField(max_length=64,blank=True,null=True,verbose_name='系统')
    memory = models.CharField(max_length=12,verbose_name=u'内存/G',blank=True,null=True)
    disk = models.CharField(max_length=12,verbose_name=u'硬盘/G',blank=True,null=True)
    user = models.ForeignKey('HostUsers', verbose_name=u'系统用户',blank=True,null=True)
    ctime = models.DateTimeField(default=datetime.now,verbose_name=u'创建时间')
    utime = models.DateTimeField(auto_now=True,verbose_name=u'更新时间')
    desc = models.CharField(max_length=200,verbose_name=u'描述',blank=True,null=True)
    server_id = models.CharField(max_length=12,blank=True,null=True,verbose_name=u'ServerID')
    game_id = models.CharField(max_length=12,blank=True,null=True,verbose_name=u'GameID')
    host_vars = models.TextField(blank=True, null=True, verbose_name='主机变量')
    def __str__(self):
        return self.wip

    def gethostname(self):
        return slugify('{0} {1} {2} {3}'.format(self.nip, self.wip, self.hostname, ''.join(
            random.choice(string.ascii_letters) for _ in range(15)).lower()))

    def getrandomid(self):
        return '{0}{1}'.format(self.pk, ''.join(random.choice(string.ascii_letters) for _ in range(15)).lower())
    class Meta:
        db_table = 'hosts'
        verbose_name = u'资产'
        verbose_name_plural = verbose_name
        permissions = (
            ("can_connect_serverinfo", "可以连接主机"),
            ("can_kill_serverinfo", "可以强制用户下线"),
            ("can_monitor_serverinfo","可以查看录像"),
            ("can_view_serverinfo", "可以查看主机"),
            ("can_filemanage_serverinfo", "可以管理文件"),
        )



class  HostUsers(models.Model):
    name = models.CharField(max_length=32,unique=True,verbose_name=u'名称')
    auth_method_choices = (
        ('ssh-password','SSH/Password'),
        ('ssh-key','SSH/KEY')
    )
    auth_method = models.CharField(choices=auth_method_choices,max_length=16,verbose_name=u'认证类型',default='ssh-password')
    username = models.CharField(max_length=32,verbose_name=u'用户名')
    ssh_port = models.IntegerField(default=22,verbose_name=u'端口')
    password = models.CharField(blank=True,null=True,max_length=128,verbose_name=u'密码')
    key = models.TextField(blank=True,null=True,verbose_name='秘钥串')
    def save(self,*args,**kwargs):
        c = crypt_password.AESCipher
        self.password = c().encrypt(self.password)
        super(HostUsers,self).save(*args,**kwargs)
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'remoteuser'
        verbose_name = u'主机用户信息'
        verbose_name_plural = verbose_name

class HostGroup(models.Model):
    name = models.CharField(max_length=32,verbose_name=u'主机组名',unique=True)
    host = models.ManyToManyField('Hosts')
    ctime = models.DateTimeField(default=datetime.now,verbose_name=u'创建时间')
    utime= models.DateTimeField(auto_now=True,verbose_name=u'更新时间')
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'hostgroup'
        verbose_name = u'主机组'
        verbose_name_plural = verbose_name

class UserHostPer(models.Model):
    user = models.ForeignKey('users.UserProfile',verbose_name='用户',unique=True)

    host_groups = models.ManyToManyField(HostGroup, verbose_name='授权主机组', blank=True)
    bind_hosts = models.ManyToManyField(Hosts, verbose_name='授权主机', blank=True)
    ctime = models.DateTimeField(default=datetime.now, verbose_name=u'创建时间')
    utime = models.DateTimeField(auto_now=True, verbose_name=u'更新时间')
    def __str__(self):
        return self.user.username
    class Meta:
        db_table ='hostper'
        verbose_name = u'用户连接主机权限'
        verbose_name_plural = verbose_name

apps/users/service/routes.py
# -*- coding:utf-8 -*-
import re
from collections import OrderedDict
from django.conf import settings
from django.utils.module_loading import import_string
from django.urls import RegexURLResolver, RegexURLPattern


def check_url_exclude(url):
    """
    排除一些特定的URL
    :param url:
    :return:
    """
    for regex in settings.AUTO_DISCOVER_EXCLUDE:
        if re.match(regex, url):
            return True


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    """
    递归的去获取URL
    :param pre_namespace: namespace前缀，以后用户拼接name
    :param pre_url: url前缀，以后用于拼接url
    :param urlpatterns: 路由关系列表
    :param url_ordered_dict: 用于保存递归中获取的所有路由
    :return:
    """
    for item in urlpatterns:
        if isinstance(item, RegexURLPattern):  # 非路由分发，讲路由添加到url_ordered_dict
            if not item.name:
                continue

            if pre_namespace:
                name = "%s:%s" % (pre_namespace, item.name)
            else:
                name = item.name
            url = pre_url + item._regex  # /rbac/user/edit/(?P<pk>\d+)/
            url = url.replace('^', '').replace('$', '')

            if check_url_exclude(url):
                continue

            url_ordered_dict[name] = {'name': name, 'url': url}

        elif isinstance(item, RegexURLResolver):  # 路由分发，递归操作

            if pre_namespace:
                if item.namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace,)
                else:
                    namespace = item.namespace
            else:
                if item.namespace:
                    namespace = item.namespace
                else:

                    namespace = None
            recursion_urls(namespace, pre_url + item.regex.pattern, item.url_patterns, url_ordered_dict)


def get_all_url_dict():
    """
    获取项目中所有的URL（必须有name别名）
    :return:
    """
    url_ordered_dict = OrderedDict()

    md = import_string(settings.ROOT_URLCONF)  # from luff.. import urls
    recursion_urls(None, '/', md.urlpatterns, url_ordered_dict)  # 递归去获取所有的路由

    return url_ordered_dict

templates/user/delete.html
{% extends 'layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block page_title %}{{ title }}{% endblock %}
{% block content %}
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p style="font-size: 13px;"><i class="fa fa-warning" aria-hidden="true"></i> 删除后将不可恢复，请确定是否删除？</p>


                <div style="margin-top: 20px;">
                    <a href="{{ cancel }}" class="btn btn-default btn-sm">取消</a>

                    <input type="submit" class="btn btn-danger btn-sm" value="确 认">
                </div>
            </form>
        </div>

{% endblock %}

templates/user/hostpermissionlist.html
{%  extends 'layout.html' %}

{% block title %}
    主机权限列表
{%  endblock %}

{% block  content %}
<div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox ">
                        <div class="ibox-title">
                            <h5>主机权限列表</h5>
                        </div>
                        <div class="ibox-content">
                            <div style="margin-bottom: 10px">
                                <a href="{% url    'user:hostper_add' %}" class="btn btn-sm btn-primary ">添加权限</a>
                            </div>

                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>用户</th>
                                    <th>权限</th>
                                    <th>主机组</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {%  for permission in  all_permissions.object_list %}
                                <tr id="{{ permission.id }}">
                                    <td>{{ permission.id }}</td>
                                    <td>{{ permission.user.username }}</td>
                                    <td>{%  for p in  permission.permissions.all %}<a>{{ p.name }}</a><br>{% endfor %}</td>
                                    <td>{%  for g  in permission.groups.all %}<a>{{ g.name }}</a><br>{% endfor %}</td>
                                    <td>
                                <a class="btn btn-xs btn-info" href="{%  url 'user:hostper_update' permission.id %}">更新主机权限</a>
                                <a class="btn btn-xs btn-danger" href="{%  url 'user:hostper_delete' permission.id %}">删除主机权限</a>
                            </td>

                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
                <div class="pageturn">
                 <ul class="pagelist">
          {% if all_permissions.has_previous %}
            <li class="long"><a href="?{{ all_permissions.previous_page_number.querystring }}">上一页</a></li>
        {% endif %}

        {% for page in all_permissions.pages %}
            {% if page %}
                {% ifequal page all_permissions.number %}
                    <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                {% else %}
                    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                {% endifequal %}
            {% else %}
                <li class="none"><a href="">...</a></li>
            {% endif %}
        {% endfor %}
        {% if all_permissions.has_next %}
            <li class="long"><a href="?{{ all_permissions.next_page_number.querystring }}">下一页</a></li>
        {% endif %}
    </ul>
</div>
            </div>
        </div>
{%  endblock %}

templates/user/rolelist.html
{%  extends 'layout.html' %}

{% block title %}
    {{ title }}
{%  endblock %}
{% block page_title %}{{ title }}{% endblock %}
{% block  content %}
<div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox ">
                        <div class="ibox-title">
                            <h5>{{ title }}</h5>
                        </div>
                        <div class="ibox-content">
                            <div style="margin-bottom: 10px">
                                <a href="{% url    'user:role_add' %}" class="btn btn-sm btn-primary ">添加角色</a>
                            </div>

                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>角色名</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {%  for role in  all_roles.object_list %}
                                <tr id="{{ role.id }}">
                                    <td>{{ role.id }}</td>
                                    <td>{{ role.title }}</td>
                                    <td class="text-navy">
                                <a class="btn btn-xs btn-info" href="{% url 'user:role_update' role.id %}">更新角色信息</a>
                                <a class="btn btn-xs btn-danger" href="{% url 'user:role_delete' role.id %}">删除角色</a>
                            </td>

                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
                <div class="pageturn">
                 <ul class="pagelist">
          {% if all_roles.has_previous %}
            <li class="long"><a href="?{{ all_roles.previous_page_number.querystring }}">上一页</a></li>
        {% endif %}

        {% for page in all_roles.pages %}
            {% if page %}
                {% ifequal page all_roles.number %}
                    <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                {% else %}
                    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                {% endifequal %}
            {% else %}
                <li class="none"><a href="">...</a></li>
            {% endif %}
        {% endfor %}
        {% if all_roles.has_next %}
            <li class="long"><a href="?{{ all_roles.next_page_number.querystring }}">下一页</a></li>
        {% endif %}
    </ul>
</div>
            </div>
        </div>
{%  endblock %}

templates/user/userlist.html
{%  extends 'layout.html' %}

{% block title %}
    {{ title }}
{%  endblock %}
<h2>{%  block page_title %}{{ title }}{% endblock %}</h2>
{% block  content %}
<div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox ">
                        <div class="ibox-title">
                            <h5>{{ title }}</h5>
                        </div>
                        <div class="ibox-content">
                            <div style="margin-bottom: 10px">
                                <a href="{% url    'user:register' %}" class="btn btn-sm btn-primary ">添加用户</a>
                            </div>

                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>用户名</th>
                                    <th>邮箱</th>
                                    <th>姓名</th>
                                    <th>手机</th>
                                    <th>权限</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {%  for user in  all_users.object_list %}
                                <tr id="{{ user.id }}">
                                    <td>{{ user.id }}</td>
                                    <td>{{ user.username }}</td>
                                    <td>{{ user.email }}</td>
                                    <td>{{ user.name }}</td>
                                    <td>{{ user.mobile }}</td>
                                    <td>{%  for role  in  user.roles.all  %}
                                        <span>{{ role.title }}
                                            {% if not forloop.last%},{% endif %}
                                        </span>
                                    {% endfor %}</td>
                                    <td class="text-navy">
                                <a class="btn btn-xs btn-info" href="{% url 'user:user_update' user.id %}">更新用户信息</a>
                                <a class="btn btn-xs btn-danger" href="{% url 'user:user_delete'  user.id %}">删除用户</a>
                            </td>

                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
                <div class="pageturn">
                 <ul class="pagelist">
          {% if all_users.has_previous %}
            <li class="long"><a href="?{{ all_users.previous_page_number.querystring }}">上一页</a></li>
        {% endif %}

        {% for page in all_users.pages %}
            {% if page %}
                {% ifequal page all_users.number %}
                    <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                {% else %}
                    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                {% endifequal %}
            {% else %}
                <li class="none"><a href="">...</a></li>
            {% endif %}
        {% endfor %}
        {% if all_users.has_next %}
            <li class="long"><a href="?{{ all_users.next_page_number.querystring }}">下一页</a></li>
        {% endif %}
    </ul>
</div>
            </div>
        </div>
{%  endblock %}